Refactor
mairatma/metal pull request #234
Opened 2017-05-04 21:50 UTC by bryceosterhaus

@mthadley, what do you think about this?

2017-05-04 22:04 UTC, mthadley commented
🎉 Very nice! Just one more nitpick. We have docs for `oneOfType` and `shapeOf`, but is there any reason not to also document the rest of them? They are still methods on `Config`, after all.

2017-05-04 22:06 UTC, mthadley requested changes

2017-05-04 22:06 UTC, mthadley commented on packages/metal-state/src/Config.js
> +	/**
Missing a description here.

2017-05-04 22:06 UTC, mthadley commented on packages/metal-state/src/Config.js
> +	/**
Missing a description here.

2017-05-04 22:42 UTC, bryceosterhaus commented
Reason I didnt add docs for the rest of them is because the functions called are documented. I can add docs to everything, just wasnt sure.

2017-05-04 22:47 UTC, bryceosterhaus commented
Updated docs

2017-05-04 22:50 UTC, mthadley commented
@bryceosterhaus  I see. However, that doesn't mean that those methods are documented.

As an example, if you were to generate a documentation site from this file, those methods would not be documented.

2017-05-04 23:26 UTC, bryceosterhaus commented
Added separate commit to further document methods in config.

2017-05-04 23:40 UTC, mthadley commented
👍 👍 Really nice @bryceosterhaus 😍 😍 

Because of the usage for the more advanced validators is a little different, I'm hoping those extra docs will make it more obvious:

```js
MyComponent.STATE = {
  user: Config.shapeOf({
    /**
     * We actually have nested Config objects here, but only certain objects
     * make sense. In other words, you can't have `Config.value('Bryce')` here.
     * But `ConfigWithValidator` should be a nice hint.
     */
    name: Config.string(),
    age: Config.number()
  })
}
```

2017-05-05 08:01 UTC, yuchi commented
Could you update the title of the issue? I had a mini heart attack thinking it would be a Metal refactor :)

2017-05-05 14:13 UTC, bryceosterhaus commented
hahah yes I will update it, definitely don't want a full metal refactor

2017-05-12 10:04 UTC, jbalsas commented
Hey @bryceosterhaus, @mthadley, is this ready to be merged? I can do so if you both are happy with it.

2017-05-12 15:05 UTC, bryceosterhaus commented
@jbalsas lgtm

2017-05-12 16:37 UTC, mthadley commented
@jbalsas I think it is good to go.

2017-05-16 10:46 UTC, jbalsas requested changes

2017-05-16 10:46 UTC, jbalsas commented on packages/metal-state/src/Config.js
> +	* A number, or a string containing a number.
I guess this description isn't really what a `ConfigWithValidator` is?

2017-05-16 15:15 UTC, bryceosterhaus commented
@jbalsas, updated the description of `ConfigWithValidator`

2017-05-17 09:29 UTC, merged