Improve error message when using `oneOf` validation. Fixes #254
mairatma/metal pull request #272
Opened 2017-10-06 21:42 UTC by Robert-Frampton

2017-10-10 11:22 UTC, jbalsas requested changes
Hey @Robert-Frampton, should we add a test for this?

2017-10-10 11:22 UTC, jbalsas commented on packages/metal-state/src/validators.js
> + * Composes an error message for Conifg.oneOf validator.
Possible typo: `Conifg.oneOf` -> `Config.oneOf`

2017-10-10 15:44 UTC, Robert-Frampton commented
We don't currently test the contents of any error messages, we only test that an error is returned or not given the input. We can add tests for this, but if we do we should probably add tests for the other use cases as well.

2017-10-10 15:46 UTC, jbalsas commented
Sounds good, just the typo, then 👍

2017-10-11 10:05 UTC, merged

2017-10-16 17:34 UTC, diegonvs commented
Hey @Robert-Frampton i was reviewing that tests and i've started a discussion here:
https://github.com/metal/metal.js/issues/277