WIP: #374
mairatma/metal pull request #376
Opened 2018-05-15 21:48 UTC by diegonvs

2018-05-16 18:43 UTC, diegonvs commented
depends on #377

2018-05-16 19:38 UTC, diegonvs commented
I'm working in tests for this use case.

2018-07-18 07:26 UTC, jbalsas requested changes
Hey @diegonvs, this looks good! I think it can be simplified a little bit.

We probably don't need to keep `array.dedupe` moving forward, as it's pretty straightforward to do it using a `Set`.

I'm pinging @bryceosterhaus and @mthadley to validate this as well.

Thanks! :)

2018-07-18 22:00 UTC, diegonvs commented on packages/metal/src/array/array.js
> +		return deduped;
https://jsperf.com/filter-vs-for-to-dedupe-an-array

2018-07-18 22:00 UTC, diegonvs commented on packages/metal-jsx/src/JSXDataManager.js
> +		);
Sounds good, I'll use it.

2018-07-19 07:20 UTC, jbalsas commented on packages/metal/src/array/array.js
> +		return deduped;
That's a premature optimization. We can get there if needed :)

2018-07-19 07:23 UTC, jbalsas commented on packages/metal/src/array/array.js
> +		return deduped;
In any case, since we're not going to need it for now, let's simply remove it

2018-07-19 16:56 UTC, diegonvs commented on packages/metal/src/array/array.js
> +		return deduped;
Okay 😂

2018-07-20 11:25 UTC, jbalsas approved these changes

2018-07-20 11:25 UTC, merged